// packages/precept-vue/src/Tabs.jsx
import { ref, computed, h } from 'vue';
import { getTabsSchema } from 'precept';
import { nanoid } from 'nanoid';
import countChildren from './helpers/countChildren';
import findChild from './helpers/findChild';

const TabsPanel = {
    name: 'TabsPanel',
    setup(props, context) {
        return () => (
            <div>{context.slots.default ? context.slots.default() : ''}</div>
        );
    },
};

const TabsTablist = {
    name: 'TabsTablist',
    setup(props, context) {
        return () => (
            <div>{context.slots.default ? context.slots.default() : ''}</div>
        );
    },
};

const TabsTab = {
    name: 'TabsTab',
    setup(props, context) {
        return () => (
            <button>
                {context.slots.default ? context.slots.default() : ''}
            </button>
        );
    },
};

const Tabs = {
    name: 'Tabs',
    props: {
        manual: {
            type: Boolean,
            default: false,
        },
    },
    setup(props, context) {
        const activeTab = ref(0);
        const tabs = ref([]);
        const { value: manual } = ref(props.manual);
        const { value: uniqueId } = computed(() => nanoid(8));
        const tablist = findChild(context.slots, TabsTablist);
        const getTabElementRef = (tabNumber) => {
            return (element) => {
                tabs.value[tabNumber] = element.$el;
            };
        };

        return () => {
            const { htmlAttributes, eventHandlers } = getTabsSchema({
                activeTab: activeTab.value,
                uniqueId,
                manual,
                totalTabs: countChildren(tablist?.children, TabsTab),
                totalPanels: countChildren(context.slots, TabsPanel),
                changeTab: (tabNumber) => {
                    activeTab.value = tabNumber;
                },
                focusOnTab: (tabNumber) => {
                    tabs.value[tabNumber].focus();
                },
            });

            let tabCount = -1;
            let panelCount = -1;

            return (
                <div>
                    {context.slots.default().map((child) => {
                        if (child.type === TabsTablist) {
                            const tablistChildren = child.children
                                .default()
                                .map((tablistChild) => {
                                    tabCount += 1;

                                    if (tablistChild.type === TabsTab) {
                                        return h(
                                            TabsTab,
                                            {
                                                ...tablistChild.props,
                                                ...htmlAttributes.tabs[
                                                    tabCount
                                                ],
                                                onClick:
                                                    eventHandlers.tabs[tabCount]
                                                        .click,
                                                onFocus:
                                                    eventHandlers.tabs[tabCount]
                                                        .focus,
                                                onKeydown:
                                                    eventHandlers.tabs[tabCount]
                                                        .keydown,
                                                ref: getTabElementRef(tabCount),
                                            },
                                            tablistChild.children
                                        );
                                    }

                                    return tablistChild;
                                });

                            return h(
                                TabsTablist,
                                {
                                    ...child.props,
                                    ...htmlAttributes.tablist,
                                },
                                () => tablistChildren
                            );
                        }

                        if (child.type === TabsPanel) {
                            panelCount += 1;

                            return h(
                                TabsPanel,
                                {
                                    ...child.props,
                                    ...htmlAttributes.panels[panelCount],
                                },
                                child.children
                            );
                        }

                        return child;
                    })}
                </div>
            );
        };
    },
};

export { Tabs, TabsPanel, TabsTablist, TabsTab };

// packages/precept-react/src/Tabs.jsx
import React, { useRef, forwardRef } from 'react';
import PropTypes from 'prop-types';
import { uncontrollable } from 'uncontrollable';
import { nanoid } from 'nanoid';
import getTabsSchema from 'precept/src/getTabsSchema';

import extendElement from './helpers/extendElement';
import isElementType from './helpers/isElementType';
import mapChildren from './helpers/mapChildren';
import countChildren from './helpers/countChildren';

const propTypes = {
    children: PropTypes.node,
    manual: PropTypes.bool,
    activeTab: PropTypes.number,
    onChange: PropTypes.func,
};

const defaultProps = {
    children: null,
    manual: false,
    activeTab: 0,
    onChange: null,
};

const TabsPanel = forwardRef(function TabsPanel(props, ref) {
    return <div {...props} ref={ref} />;
});

const TabsTab = forwardRef(function TabsTab(props, ref) {
    return <button {...props} ref={ref} />;
});

const TabsTablist = forwardRef(function TabsTablist(props, ref) {
    return <div {...props} ref={ref} />;
});

const Tabs = forwardRef(function Tabs(props, ref) {
    const { children, manual, activeTab, onChange, ...restOfProps } = props;
    const { current: uniqueId } = useRef(nanoid(8));
    const tabElements = useRef([]);
    let tabCount = -1;
    let panelCount = -1;

    const { htmlAttributes, eventHandlers } = getTabsSchema({
        uniqueId,
        manual,
        activeTab,
        changeTab: onChange,
        totalTabs: countChildren(children, TabsTab),
        totalPanels: countChildren(children, TabsPanel),
        focusOnTab: (tabNumber) => {
            tabElements.current[tabNumber].focus();
        },
    });

    const getTabElementRef = (tabNumber) => {
        return (element) => {
            tabElements.current[tabNumber] = element;
        };
    };

    return (
        <div {...restOfProps} ref={ref}>
            {mapChildren(children, (child) => {
                if (isElementType(child, TabsTablist)) {
                    return extendElement(child, htmlAttributes.tablist);
                }

                if (isElementType(child, TabsTab)) {
                    tabCount += 1;

                    return extendElement(child, {
                        ...htmlAttributes.tabs[tabCount],
                        onClick: eventHandlers.tabs[tabCount].click,
                        onFocus: eventHandlers.tabs[tabCount].focus,
                        onKeyDown: eventHandlers.tabs[tabCount].keydown,
                        ref: getTabElementRef(tabCount),
                    });
                }

                // istanbul ignore else
                if (isElementType(child, TabsPanel)) {
                    panelCount += 1;

                    return extendElement(
                        child,
                        htmlAttributes.panels[panelCount]
                    );
                }

                // istanbul ignore next
                return child;
            })}
        </div>
    );
});

Tabs.propTypes = propTypes;
Tabs.defaultProps = defaultProps;

const UncontrollableTabs = uncontrollable(Tabs, { activeTab: 'onChange' });

UncontrollableTabs.Tablist = TabsTablist;
UncontrollableTabs.Tab = TabsTab;
UncontrollableTabs.Panel = TabsPanel;

export default UncontrollableTabs;
